version: '3.8'
name: code_service
services:
  app:
    build:
      context: .
      dockerfile: deployment/image/Dockerfile_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - TZ=America/Caracas
      - PYTHONUNBUFFERED=1  # Importante para ver los logs en tiempo real
      - LOG_LEVEL=DEBUG     # Nivel de logging
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --log-level debug --reload
    restart: always