version: '3.8'
name: code_service
services:
  app:
    build:
      context: .
      dockerfile: deployment/image/Dockerfile_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - TZ=America/Caracas
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=DEBUG
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --log-level debug --reload
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  lint:
    build:
      context: .
      dockerfile: deployment/image/Dockerfile_api
    volumes:
      - .:/app
    command: >
      sh -c "
        black src/ --check &&
        flake8 src/ &&
        pylint src/"

  test:
    build:
      context: .
      dockerfile: deployment/image/Dockerfile_api
    volumes:
      - .:/app
    command: pytest tests/ -v